name: Deploy test page
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'testpage/**'
      - '.github/workflows/deploy-testpage.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - run: npm ci
      - run: |
          npm ci
          npm run build
        working-directory: testpage
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: testpage/dist
          CLEAN: true
